# Generated by Django 3.2.3 on 2021-10-16 20:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('calculatorapp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='calculatort',
            name='created',
        ),
    ]
